### ISSUE TITLE
Remove Pebble support

### ISSUE THREAD

**Issue by itachi1706** [itachi1706/SingBuses#165]
Let's face it. Most of the Pebble stuff are basically gone or removed for a while now. It makes no logical sense to retain it in the app especially because Q will remove the storage permissions necessary to store the pebble software in SD so that the Pebble app can read it. Hence let's remove it. Android Wear support is still planned as a replacement. Maybe. 

Goodbye Pebble. You were good while you lasted 😭

**TODO** 
- [ ] Remove Pebble code from Android app (we can move it to somewhere I guess in a zip file)
- [ ] Remove Pebble C code from repo (store in zip file)
- [ ] Move those zip file to a /pebble folder
- [ ] Remove/Hide the Companion App Install button on the main menu
- [ ] hide the Companion App selection options in the settings menu
- [ ] Test to make sure nothing breaks further

_Sent from my LG G7 ThinQ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
